"""Pydantic schemas for LLM-assisted goal compilation and funnel assumptions."""

from typing import Any

from pydantic import BaseModel, Field

from pilot.schemas.goal import TargetSpec


class FunnelAssumptions(BaseModel):
    """Conversion probability priors for back-solving required funnel milestones."""

    application_to_response: float = Field(
        gt=0.0,
        le=1.0,
        description="Conversion probability from submitted application to company response",
    )
    response_to_interview: float = Field(
        gt=0.0,
        le=1.0,
        description="Conversion probability from response to first-round interview",
    )
    interview_to_offer: float = Field(
        gt=0.0,
        le=1.0,
        description="Conversion probability from interview stage to formal job offer",
    )
    sourcing_to_application: float = Field(
        default=0.5,
        gt=0.0,
        le=1.0,
        description="Qualification rate from sourced roles to submitted applications",
    )


class CompiledGoalDraft(BaseModel):
    """Draft goal generated by structured LLM prior to Python back-solving and sanitization."""

    target_spec: TargetSpec
    success_criteria: dict[str, Any] = Field(
        default_factory=dict,
        description="Success criteria dictionary proposed by LLM (sanitized to numeric-only in compiler)",
    )
    funnel_assumptions: FunnelAssumptions
